# Generated by Django 5.1.1 on 2024-09-30 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6, verbose_name='Gender')),
                ('date_of_birth', models.CharField(max_length=100, verbose_name='Date of Birth')),
                ('place_of_residence', models.CharField(blank=True, max_length=255, null=True, verbose_name='Place of Residence')),
                ('relocate', models.BooleanField(verbose_name='Relocate')),
                ('names_of_hobby', models.CharField(blank=True, max_length=255, null=True, verbose_name='Names of Hobby')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('hard_skills', models.TextField(verbose_name='Hard Skills')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=255, verbose_name='Language Name')),
                ('level', models.CharField(max_length=100, verbose_name='Level')),
                ('certificate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Certificate')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_languages', to='api.personaldetails', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=255, null=True, verbose_name='University')),
                ('courses', models.TextField(blank=True, null=True, verbose_name='Courses')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.personaldetails', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
                ('social_media', models.CharField(blank=True, max_length=255, null=True, verbose_name='Social Media')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.personaldetails', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_of_publication', models.CharField(max_length=255, verbose_name='Title of Publication')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.personaldetails', verbose_name='Person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Position')),
                ('place_of_work', models.CharField(max_length=255, verbose_name='Place of Work')),
                ('onboarding_date', models.CharField(max_length=100, verbose_name='Onboarding Date')),
                ('offboarding_date', models.CharField(blank=True, default='-', max_length=100, verbose_name='Offboarding Date')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='api.personaldetails', verbose_name='Person')),
            ],
        ),
    ]
