# Generated by Django 5.1.1 on 2024-10-03 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foreignlanguages',
            name='person',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='person',
        ),
        migrations.RemoveField(
            model_name='education',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='hard_skills',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='summary',
        ),
        migrations.AddField(
            model_name='education',
            name='date_of_publication',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='education_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='name_of_publication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='publication_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='year_of_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='year_of_start',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='email',
            field=models.EmailField(default='<EMAIL>', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='photos_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='additional_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='date_of_birth',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=6),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='names_of_hobby',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='place_of_residence',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='relocate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='offboarding_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='onboarding_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='place_of_work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_skills', models.CharField(max_length=255)),
                ('soft_skills', models.CharField(max_length=255)),
                ('name_of_language', models.CharField(max_length=255)),
                ('level_of_language', models.CharField(max_length=255)),
                ('certification', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.personaldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='ForeignLanguages',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
