# Generated by Django 5.1.1 on 2024-10-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_foreignlanguages_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='offboarding_date',
            field=models.CharField(blank=True, default='-', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='api.personaldetails'),
        ),
    ]
