# Generated by Django 5.1.1 on 2024-10-03 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_education_person_alter_skills_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_link',
        ),
    ]
