# Generated by Django 5.1.1 on 2024-10-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_education_education_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='university',
            new_name='educational_organisation',
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_end',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='year_of_start',
            field=models.IntegerField(blank=True, default='-', null=True),
        ),
    ]
