# Generated by Django 5.1.1 on 2024-10-09 14:11

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_workexperience_additional_information'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summary',
            name='person',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date_of_publication',
        ),
        migrations.RemoveField(
            model_name='education',
            name='name_of_publication',
        ),
        migrations.RemoveField(
            model_name='education',
            name='publication_link',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='social_media',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='hard_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='soft_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='summary',
            field=models.TextField(default='No summary'),
        ),
        migrations.AlterField(
            model_name='education',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='api.personaldetails'),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='names_of_hobby',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experience', to='api.personaldetails'),
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_language', models.CharField(max_length=255)),
                ('level_of_language', models.CharField(max_length=255)),
                ('certification', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='api.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_publication', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_publication', models.DateField(blank=True, null=True)),
                ('publication_link', models.URLField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='api.personaldetails')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_social_media', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media', to='api.personaldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='Skills',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
