# Generated by Django 5.1.1 on 2024-11-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_personaldetails_hard_skills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='photos_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
